"""flights

Revision ID: 96d325c199d0
Revises: ec2ba224179e
Create Date: 2025-07-09 15:43:58.384626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d325c199d0'
down_revision: Union[str, Sequence[str], None] = 'ec2ba224179e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('origin_city_id', sa.String(length=36), nullable=False),
    sa.Column('destination_city_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'BOARDING', 'DEPARTED', 'ARRIVED', 'DELAYED', 'CANCELED', name='flight_status'), nullable=False),
    sa.Column('departure', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_destination_city_id'), 'flights', ['destination_city_id'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=True)
    op.create_index(op.f('ix_flights_origin_city_id'), 'flights', ['origin_city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_origin_city_id'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination_city_id'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
